home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path('', views.index, name='index'),
]

linem/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from maincms import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('maincms/', include('maincms.urls', namespace='maincms')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maincms/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import user_passes_test
from . import views

app_name = "maincms"
#def superuser_required(view_func):
#    return user_passes_test(lambda u: u.is_superuser, login_url='/no-access/')(view_func)


urlpatterns = [
    #path('', superuser_required(views.maincms_in), name='maincms_in'),
    path('', views.maincms_in, name='maincms_in'),
    path('Artist_list.html', views.Artists, name='Artists'),
    path('Artist_create.html', views.create_artist, name='create_artist'),
    path('album_create.html', views.create_album, name='create_album'),
    path('test.html', views.test_go, name='test_test'),
    path('rightholder_cr.html', views.rightholder_cr_view, name='rightholder_cr'),
    path('rightholder_list.html', views.rightholder_list_view, name='rightholder_view'),
    path('api/artists/', views.get_artist_profiles, name='get_artist_profiles'),
    path('api/rightholder/', views.get_rightholder_profiles, name='get_rightholder_profiles'),
    path("save_album/", views.save_album, name="save_album"),
    path('artists/<int:artist_id>/', views.artist_detail),
    path('artists/<int:artist_id>/update/', views.artist_update, name='artist_update'),
    path('artists/<int:artist_id>/delete/', views.artist_delete, name='artist_delete'),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maincms/forms.py
from django import forms
from maincms.models import create_Artist_profile, test, rightholder_cr,Album

class Artist_create_form(forms.ModelForm):
    class Meta:
        model = create_Artist_profile
        fields = ['Artist_name','Artist_name_en','sex','category','Albums','Melon_ID','Apple_url','Spotify_ID','Youtube_ID','Artist_image' ]

class test_form(forms.ModelForm):
        class Meta:
            model = test
            fields = ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7']

class rightholder_cr_form(forms.ModelForm):
     class Meta:
          model = rightholder_cr
          fields = ['user_id','user_name','email', 'phone','bank_name','account_number','account_holder','user_level','user_type','registration_num','contract_date','expiration_date',]

class Create_album_form(forms.ModelForm):
     class Meta:
          model = Album
          fields = ['album_code','album_title','album_title_en','album_artist','album_genre','album_Categ']

maincms/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import create_Artist_profile, album_genres, album_Category, test, rightholder_cr, Album, Track,Accounting_base
from django.http import HttpResponse
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import Artist_create_form, test_form,rightholder_cr_form,Create_album_form
from django.db.models import Q 
from django.core.paginator import Paginator
import json
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings
import os


# Create your views here.

def get_artist_profiles(request):
    # 페이지 번호와 페이지 크기 받아오기
    page = request.GET.get('page', 1)
    page_size = request.GET.get('page_size', 10)
    search_query = request.GET.get('search', '').strip().lower()  # 검색어 가져오기

    # 아티스트 데이터 필터링
    artists = create_Artist_profile.objects.all()

    if search_query:
        artists = artists.filter(
            Q(Artist_name__icontains=search_query) |  # 이름에 검색어 포함
            Q(Artist_name_en__icontains=search_query)  # 영어 이름에 검색어 포함
        )

    # 페이징 처리
    paginator = Paginator(artists.values('Artist_name', 'Artist_ID', 'Artist_image', 'category').order_by('id'),page_size)

    try:
        artists_page = paginator.page(page)
    except Exception as e:
        return JsonResponse({'error': 'Invalid page'}, status=400)

    # 데이터와 페이지 정보를 반환
    return JsonResponse({
        'artists': list(artists_page.object_list),
        'has_next': artists_page.has_next(),
        'has_previous': artists_page.has_previous(),
        'current_page': artists_page.number,
        'total_pages': paginator.num_pages,
    })

def get_rightholder_profiles(request):
    # 페이지 번호와 페이지 크기 받아오기
    page = request.GET.get('page', 1)
    page_size = request.GET.get('page_size', 10)
    search_query = request.GET.get('search', '').strip().lower()  # 검색어 가져오기

    # 권리자 데이터 필터링
    rightholder = rightholder_cr.objects.all()

    if search_query:
        rightholder = rightholder.filter(
            Q(user_name__icontains=search_query) |  # 이름에 검색어 포함
            Q(email__icontains=search_query)  # 이메일에 검색어 포함
        )

    # 페이징 처리
    paginator = Paginator(rightholder.values('user_name','user_code','email','user_level').order_by('id'), page_size)

    try:
        rightholder_page = paginator.page(page)
    except Exception as e:
        return JsonResponse({'error': 'Invalid page'}, status=400)

    # 데이터와 페이지 정보를 반환
    return JsonResponse({
        'rightholders': list(rightholder_page.object_list),
        'has_next': rightholder_page.has_next(),
        'has_previous': rightholder_page.has_previous(),
        'current_page': rightholder_page.number,
        'total_pages': paginator.num_pages,
    })

def maincms_in(request):
    return render(request, 'maincms/index.html')

def increment_value(value):
    # 문자열에서 숫자와 문자 분리
    prefix = ''.join(filter(str.isalpha, value))  # 문자 부분 (A)
    number = ''.join(filter(str.isdigit, value))  # 숫자 부분 (10000001)

    # 숫자를 증가시키기
    incremented_number = int(number) + 1

    # 숫자를 다시 0으로 패딩하여 결합
    return f"{prefix}{incremented_number:08d}"

def rightholder_cr_view(request):
    num = rightholder_cr.objects.last().id
    num = num - 1
    list = rightholder_cr.objects.values()
    vv = list[num]['user_code']
    new_value = increment_value(vv)

    if request.method == 'POST':
        form = rightholder_cr_form(request.POST)
        if form.is_valid():
            create = form.save(commit=False)
            create.user_code = new_value
            create.save()
            return redirect('maincms:rightholder_cr')
    else:   
        form = rightholder_cr_form()
    context = {'form' : form}
    return render(request, 'maincms/rightholder_cr.html' ,context)

def rightholder_list_view(request):

    """
    목록 출력 + 검색 필드 선택 기능
    """
    query = request.GET.get('q', '')  # 검색어
    field = request.GET.get('field', 'user_name')  # 검색 필드 (기본값: user_name)

    # 유효한 필드인지 확인
    valid_fields = ['user_name', 'email']
    if field not in valid_fields:
        field = 'user_name'

    if query:
        # 검색 필드와 검색어로 필터링
        filter_kwargs = {f"{field}__icontains": query}
        rightholder_list = rightholder_cr.objects.filter(**filter_kwargs).order_by('-create_date')
    else:
        rightholder_list = rightholder_cr.objects.order_by('-create_date')

    context = { 'rightholder_list' : rightholder_list, 'query': query, 'field': field, 'valid_fields': valid_fields }
    return render(request, 'maincms/rightholder_list.html' ,context)

@csrf_exempt
def test_go(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        print(data['test1'])
        print(type(data))
        form = test_form()
        try_test = form.save(commit=False)
        try_test.test1 = data['test1']
        try_test.test2 = data['test2']
        try_test.test3 = data['test3']
        try_test.test4 = data['test4']
        try_test.test5 = data['test5']
        try_test.test6 = data['test6']
        try_test.test7 = data['test7']
        try_test.save()
        
    return render(request, 'maincms/test.html')

# 앨범 등록 기능 개발 중
@csrf_exempt
def create_album(request):
        
    return render(request, 'maincms/album_create.html')


@csrf_exempt
def save_album(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)  # JSON 데이터 파싱
            album_data = data.get("album")
            track_data = data.get("tracks", [])
            right_data = data.get("rights")
            artist_data = data.get("artists")

            album_Categ = album_data.get("album_Categ", "")
            album_code = album_data.get("albumcode", "")
            opendate = album_data.get("opendate", "")
            track_no = [t.get("track_no", 0) for t in track_data]
            user_c = right_data.get("rightholder")
            user_ac = right_data.get("User_Fees")

            if not track_data:
                return JsonResponse({"error": "트랙 정보가 없습니다."}, status=400)
            
            # 앨범 코드 작성
            #last_album = Album.objects.last()
            #num = last_album.id if last_album else 0  # None 방지

            #if num is None:
            #    num = 0
            #else:
            #    num -= 1

            # Album 객체 목록 가져오기
            #album_list = list(Album.objects.values())

            #if num < 0 or num >= len(album_list):  # 인덱스 유효성 체크
            #    code = "0001"
            #else:
            #    code = album_list[num].get('album_code', "0001")

            # 코드 변환 로직
            #if str(code) == "0" or not code:
            #    code = "0001"
            #elif len(code) >= 7:
            #    code = code[7:]
            #    code = str(int(code) + 1).zfill(4)

            # 앨범 카테고리 변환
            #album_Categ = album_Categ or "기타"
            #tag_dict = {
            #    "정규": "03",
            #    "싱글": "01",
            #    "EP": "02"
            #}
            #tag = tag_dict.get(album_Categ, "04")

            # 개봉일 처리
            #if opendate and len(opendate) >= 4:
            #    ddd = opendate[2:4]
            #else:
            #    ddd = "00"

            # 최종 코드 조합
            #ALBC = f"LA{ddd}{tag}-{code}"
            ALBC = album_code
            print(ALBC)  # 생성된 앨범 코드 출력

            # 앨범 저장
            album = Album.objects.create(
                album_code=ALBC,  # 자동 코드 생성
                album_title=album_data["album_title"],
                album_title_en=album_data["album_title_en"],
                album_artist=album_data["album_artist"],
                album_genre=album_data["album_genre"],
                album_Categ=album_data["album_Categ"],
                album_country=album_data["album_country"],
                startdate=album_data["startdate"],
                opendate=album_data["opendate"],
                service_time=album_data["service_time"],
                album_copyright=album_data["album_copyright"],
                album_publish=album_data["album_publish"],
                service_area=album_data["service_area"],
                excluded=album_data["excluded"],
                service_lang=album_data["service_lang"],
                UPC_code=album_data["UPC_code"],
                UCI_code=album_data["UCI_code"],
                YT_service=album_data["YT_service"],
                status=album_data["status"],
                with_main_artist=album_data["with_main_artist"],
                feat_main_artist=album_data["feat_main_artist"],
            )
            # ✅ 아티스트 처리
            main_artist_id = artist_data.get('main_artist_id', '')
            if not main_artist_id:
                return JsonResponse({'status': 'error', 'message': '메인 아티스트는 필수입니다.'}, status=400)

            main_artist_list = main_artist_id.split(',')
            with_artist_id_list = artist_data.get('with_main_artist_id', '').split(',') if artist_data.get('with_main_artist_id') else []
            feat_artist_id_list = artist_data.get('feat_main_artist_id', '').split(',') if artist_data.get('feat_main_artist_id') else []

            all_artist_ids = main_artist_list + with_artist_id_list + feat_artist_id_list
            for artist_id in all_artist_ids:
                try:
                    artist_profile = create_Artist_profile.objects.get(Artist_ID=artist_id)
                except create_Artist_profile.MultipleObjectsReturned:
                    return JsonResponse({"error": f"중복된 아티스트 ID: {artist_id}"}, status=400)
                except create_Artist_profile.DoesNotExist:
                    continue

                if artist_id in main_artist_list:
                    albums = json.loads(artist_profile.Albums) if artist_profile.Albums else []
                    if ALBC not in albums:

templates/maincms/Artist_list.html
{% extends 'maincms_base.html' %}
{% block content %}
{% include "maincms/navbar.html" %}

<div class=".container-fluid" style="height: 100vh; padding-top: 81px;">
    <div class="d-flex flex-row d-flex align-items-start mb-3" style="height: -webkit-fill-available;">
        <div>
            {% include "maincms/sidebar.html" %}
        </div>
        <div>
            <div class="container-lg py-3">
                {% csrf_token %}
                <h5 class="fw-bold mb-2">아티스트 검색</h5>
                <form method="get" action="{% url 'maincms:Artists' %}" class="info-field-start mb-5" style="font-size: 13px;">
                    <input type="text" name="q" class="form-tr" placeholder="아티스트 이름 검색"
                        value="{{ search_query }}">
                    <select name="field" class="form-select-sm" style="height: 31px;">
                        <option value="">카테고리 선택</option>
                        <option value="Artist_name" {% if field == "Artist_name" %}selected{% endif %}>Artist Name</option>
                        <option value="Artist_ID" {% if field == "Artist_ID" %}selected{% endif %}>Artist ID</option>
                    </select>
                    <button type="submit" class="btn btn-primary btn-sm">검색</button>
                </form>

                <h5 class="fw-bold mb-2">아티스트 리스트</h5>
                <table class="table">
                    <thead class="table-light">
                        <tr>
                        <th scope="col-1" class="text-center" style="width:50px;">NO.</th>
                        <th scope="col" class="text-center">Artist Image</th>
                        <th scope="col" class="text-center">Artist ID</th>
                        <th scope="col" class="text-center">Artist_name</th>
                        <th scope="col" class="text-center">category</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if Artist_list %}
                        {% for Artists in Artist_list %}
                        <tr style="font-size: 13px; cursor:pointer;" onclick="location.href='artists/{{ Artists.id }}'" onmouseover="this.style.backgroundColor='#f5f5f5'" onmouseout="this.style.backgroundColor=''">
                            <td class="text-center">{{ forloop.counter }}</td>
                            <td class="text-center">
                                {% if Artists.Artist_image %}
                                <img src="http://localhost:8000/media/{{ Artists.Artist_image }}" style="width: 30px;" height="30px;">
                                {% else %}
                                <img src="http://localhost:8000/media/Artist_images/user_image_none.png" style="width: 30px;" height="30px;">
                                {% endif %}
                            </td>
                            <td class="text-center">{{ Artists.Artist_ID }}</td>
                            <td class="text-center">{{ Artists.Artist_name }} 
                                {% if Artists.Artist_name_en %}
                                    ({{ Artists.Artist_name_en }})
                                {% endif %}
                                </td>
                            <td class="text-center">{{ Artists.category }}</td>
                        </tr>
                        {% endfor %}
                        {% else %}
                            <tr><td>데이터 없음</td></tr>
                        {% endif %}
                    </tbody>
                </table>
                    <a href="{% url 'maincms:create_artist' %}" class="btn btn-primary">등록하기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/maincms/ar_find_modal.html
<div class="container-lg py-3">
  <h5 class="fw-bold mb-2">아티스트 검색</h5>
  <form method="get" action="{% url 'maincms:artist_find' %}" class="info-field-start mb-5" style="font-size: 13px;">
      <input type="text" id="search-input" name="q" class="form-tr" placeholder="아티스트 이름 검색"
             value="">
      <button type="submit" class="btn btn-primary btn-sm">검색</button>
    </form>
  <h5 class="fw-bold mb-2">아티스트 리스트</h5>
  <table id="ar_fi_table">
      <thead class="table-light">
          <tr>
          <th scope="col-1" class="text-center" style="width:50px;">NO.</th>
          <th scope="col" class="text-center">Artist Image</th>
          <th scope="col" class="text-center">Artist ID</th>
          <th scope="col" class="text-center">Artist_name</th>
          <th scope="col" class="text-center">category</th>
          </tr>
      </thead>
      <tbody class="tbody">
        {% if Artist_list %}
        {% for Artists in Artist_list %}
          <tr style="font-size: 13px;">
              <td class="text-center">{{ forloop.counter }}</td>
              <td class="text-center">
                  {% if Artists.Artist_image %}
                  <img src="http://localhost:8000/media/{{ Artists.Artist_image }}" style="width: 30px;" height="30px;">
                  {% else %}
                  <img src="http://localhost:8000/media/Artist_images/user_image_none.png" style="width: 30px;" height="30px;">
                  {% endif %}
              </td>
              <td class="text-center">{{ Artists.Artist_ID }}</td>
              <td class="text-center">{{ Artists.Artist_name }}</td>
              <td class="text-center">{{ Artists.category }}</td>
          </tr>
          {% endfor %}
          {% else %}
              <tr><td>데이터 없음</td></tr>
          {% endif %}
      </tbody>
   </table>

templates/maincms/ar_navbar.html
<ul class="nav mb-3">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="{% url 'maincms:Artists' %}">아티스트 관리</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'maincms:Artists' %}">아티스트 리스트</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'maincms:create_artist' %}">아티스트 등록</a>
  </li>
</ul>

templates/maincms/artist_detail.html
{% extends 'maincms_base.html' %}
{% block content %}
{% include "maincms/navbar.html" %}

<div class=".container-fluid" style="height: 100vh; padding-top: 81px;">
    <div class="d-flex flex-row d-flex align-items-start mb-3" style="height: -webkit-fill-available;">
        <div>
            {% include "maincms/sidebar.html" %}
        </div>
        <div>
            <div class="container-lg py-3">
                <h5 class="fw-bold">아티스트 정보</h5>
                <form id="artist_create" method="post" enctype="multipart/form-data">
                    {% csrf_token %} 
                    <input type="hidden" name="artist_id" value="{{ artist_d.id }}">
                    <input type="hidden" name="Artist_ID" value="{{ artist_d.Artist_ID }}">
                    <div class="info-field-col-st mb-3">
                        <div class="info-field-start">
                            {% if artist_d.Artist_image %}
                            <img src="http://localhost:8000/media/{{ artist_d.Artist_image }}" style="width: 150px;" height="150px;">
                            {% else %}
                            <img src="http://localhost:8000/media/Artist_images/user_image_none.png" style="width: 150px;" height="150px;">
                            {% endif %}
                            <div class="info-field-column">
                                <div class="info-field-start mb-3">
                                    <div class="label-field"><i class="bi bi-check check"></i>아티스트 이름</div><input class="form-in" type="text" name="Artist_name" value="{{ artist_d.Artist_name }}">
                                    <div class="label-field"><i class="bi bi-check"></i>아티스트 이름(영문)</div><input class="form-in" type="text" name="Artist_name_en" value="{{ artist_d.Artist_name_en }}">
                                </div>
                                <div class="info-field-start mb-3">
                                    <div class="label-field" ><i class="bi bi-check check"></i>성별</div>
                                        <select class="form-select-sm" name="sex" style="width: 203px;">
                                            <option {% if artist_d.sex == "" %}selected{% endif %}>선택하세요</option>
                                            <option value="Man" {% if artist_d.sex == "Man" %}selected{% endif %}>남성</option>
                                            <option value="Female" {% if artist_d.sex == "Female" %}selected{% endif %}>여성</option>
                                            <option value="mixed" {% if artist_d.sex == "mixed" %}selected{% endif %}>혼성</option>
                                        </select>
                                        <div class="label-field"><i class="bi bi-check check"></i>유형</div>
                                        <select class="form-select-sm" name="category" style="width: 203px;">
                                            <option {% if artist_d.category == "" %}selected{% endif %}>선택하세요</option>
                                            <option value="Solo" {% if artist_d.category == "Solo" %}selected{% endif %}>솔로</option>
                                            <option value="Duo" {% if artist_d.category == "Duo" %}selected{% endif %}>듀오</option>
                                            <option value="Group" {% if artist_d.category == "Group" %}selected{% endif %}>그룹</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <h5 class="fw-bold">아티스트 url</h5>
                    <div class="info-field-column">
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Apple Url</div><input class="form-in" style="width: 400px;" type="text" name="Apple_url" value="{{ artist_d.Apple_url }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Spotify Url</div><input class="form-in" style="width: 400px;" type="text" name="Spotify_ID" value="{{ artist_d.Spotify_ID }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Melon Url</div><input class="form-in" style="width: 400px;" type="text" name="Melon_ID" value="{{ artist_d.Melon_ID }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Genie Url</div><input class="form-in" style="width: 400px;" type="text" name="genie_url" value="{{ artist_d.genie_url }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Bugs Url</div><input class="form-in" style="width: 400px;" type="text" name="bugs_url" value="{{ artist_d.bugs_url }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Flo Url</div><input class="form-in" style="width: 400px;" type="text" name="flo_url" value="{{ artist_d.flo_url }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Vibe Url</div><input class="form-in" style="width: 400px;" type="text" name="vibe_url" value="{{ artist_d.vibe_url }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>Youtube Topic</div><input class="form-in" style="width: 400px;" type="text" name="Youtube_ID" value="{{ artist_d.Youtube_ID }}">
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>아티스트 이미지</div><input class="form-control form-control-sm" style="width: 400px;" type="file" id="Artist_image" name="Artist_image">
                        </div>
                    </div>
                    <h5 class="fw-bold">아티스트 설명</h5>
                    <div class="info-field-column">
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>아티스트 소개</div><textarea class="form-control" type="text" name="bio" rows="3"></textarea>
                        </div>
                        <div class="info-field-start mb-3">
                            <div class="label-field"><i class="bi bi-check"></i>비고</div><textarea class="form-control" type="text" name="artist_etc" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="info-field-column">
                        <button type="submit" class="btn btn-primary" formaction="{% url 'maincms:artist_update' artist_d.id %}">수정하기</button>
                        <button type="submit" class="btn btn-danger" formaction="{% url 'maincms:artist_delete' artist_d.id %}" onclick="return confirm('정말 삭제하시겠습니까?');">삭제하기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

    {% endblock %}

templates/maincms/index.html
{% extends 'maincms_base.html' %}
{% block content %}
{% include "maincms/navbar.html" %}
<div class=".container-fluid" style="height: 100vh; padding-top: 81px;">
    <div class="d-flex flex-row d-flex align-items-start mb-3" style="height: -webkit-fill-available;">
        <div>
            {% include "maincms/sidebar.html" %}
        </div>
        <div>
            <h1>메인페이지</h1>
        </div>
    </div>
</div>
{% endblock %}

templates/maincms/navbar.html
<div class="container-fluid position-absolute px-0">
  <nav class="navbar navbar-expand-lg shadow bg-body-tertiary">
    <div class="container-fluid mx-3" style="height:65px;" style="position: absolute;">
      <a class="navbar-brand" href="{% url 'maincms:maincms_in' %}"><img src="../media/linem_logo_white.png" style="height: 35px;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'maincms:create_album' %}">음원등록</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">음원리스트</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'maincms:Artists' %}">아티스트 관리</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'maincms:rightholder_view' %}">권리자 관리</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'maincms:test_test' %}">테스트페이지</a>
          </li>
        </ul>
        <span class="navbar-text">
          (Setting) login
        </span>
      </div>
    </div>
  </nav>
</div>

templates/maincms/rh_navbar.html
<nav class="navbar navbar-expand-lg mb-3 bg-body-tertiary">
    <div class="container-fluid">
      <a class="nav-link" href="{% url 'maincms:rightholder_view' %}"><i class="bi bi-house"></i>권리자 관리</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'maincms:rightholder_cr' %}">: 권리자 등록</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'maincms:rightholder_view' %}">: 권리자 리스트</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- 아 괜히 그림자 넣어가지고 시발 이것도 바꿔야함 -->